### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by burnhaj** [mzac/docker-rtl_sdr-broadcastify#1]
Did you miss a step in your instructions?  I can't get past the checking to see that docker was installed properly.
pi@raspberrypi:~ $ docker info
Client:
 Debug Mode: false

Server:
ERROR: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info: dial unix /var/run/docker.sock: connect: permission denied
errors pretty printing info
pi@raspberrypi:~ $ 

Isn't there a step needed about adding user pi to the docker group?

Thanks for posting this.

**Comment by mzac** [comment]
Is this what you were looking for?

Look at this commit: afa300282c1f30947908886522ac367d04445a7c

**Comment by burnhaj** [comment]
Yes, that does it.   Since I was working as the pi user on the pi, i found it also necessary to go root to run the blacklist lines.  I am no expert at this stuff but can usually stumble through it. i have gotten your image working.  Now on to the root of my problem, I have never found the correct combination of offset, squelch, and gain.  My audio has always been just awful. thanks for posting your work.
---------- Original Message ----------

**Comment by mzac** [comment]
Yes I've had a hard time finding the PPS and gain.  What I did to test is ran 'rtl_tcp' and connected with SDR Sharp and then tuned to our local weather station on 162.550 MHZ.  It is a very narrow signal so with that I was able to determine my PPS of 62.  As for the gain, I usually put the highest and it works best.

Good luck!
